{{- if and (not .Values.postgresql.existingSecret) (not .Values.postgresql.password) }}
  {{- fail "postgresql.password is required when postgresql.existingSecret is not set" }}
{{- end }}
{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timescale.fullname" . }}-credentials
  labels:
    {{- include "timescale.labels" . | nindent 4 }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}