{{- if not .Values.postgresql.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-chart.fullname" . }}-credentials
  labels:
    app.kubernetes.io/name: {{ include "my-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
type: Opaque
data:
  postgres-password: {{ (default (randAlphaNum 16) .Values.postgresql.password) | b64enc | quote }}  
{{- end }}