apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "my-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database    
    helm.sh/chart: {{ include "my-chart.chart" . }}
spec:
  type: {{ .Values.service.type }}      
  selector:
    app.kubernetes.io/name: {{ include "my-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: database
  
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5432
    protocol: TCP