apiVersion: v1
kind: Service
metadata:
  name: {{ include "timescale.fullname" . }}
  labels:
    {{- include "timescale.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "timescale.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5432
    protocol: TCP